# version: '3.8'
services:
  waf-nginx:
    build:
      context: ./waf-nginx-crs
      dockerfile: Dockerfile
    container_name: dpu-waf-nginx-crs
    ports:
      - "80:8080"
        # - "443:8443"
    networks:
        - backnet
        - frontnet
    volumes:
      - ./waf-nginx-crs/logs:/var/log/nginx
      - ./waf-nginx-crs/logs:/var/log
    restart: unless-stopped

  web:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    container_name: dpu-web
    networks:
      - backnet

networks:
    backnet:
      driver: bridge
      internal: true
    frontnet:
      driver: bridge
